services:
  - type: web
    name: ion-bot-web      
    runtime: python
    plan: free            
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /    
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3     

  - type: worker
    name: ion-bot-worker   
    runtime: python
    plan: free            
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3     